image: debian

stages:
  - Version
  - Compile
  
Version:
    stage: Version
    script:
        - whoami
        
Compile:
    stage: Compile
    script:
        - sdk/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
