# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SimpleLinux.xdc

# Block Designs: bd/ProcessingSystem/ProcessingSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem || ORIG_REF_NAME==ProcessingSystem} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_processing_system7_0_0 || ORIG_REF_NAME==ProcessingSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_proc_sys_reset_0_0/ProcessingSystem_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_proc_sys_reset_0_0 || ORIG_REF_NAME==ProcessingSystem_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_axi_gpio_0_0/ProcessingSystem_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_axi_gpio_0_0 || ORIG_REF_NAME==ProcessingSystem_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_ps7_0_axi_periph_0/ProcessingSystem_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==ProcessingSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_auto_pc_0/ProcessingSystem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_auto_pc_0 || ORIG_REF_NAME==ProcessingSystem_auto_pc_0} -quiet] -quiet

# XDC: bd/ProcessingSystem/ProcessingSystem_ooc.xdc
