webtalk_init -webtalk_dir /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-05-05 21:23:55" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210727995_1777512417_210616669_940" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tid1gnl31d5vum6tcjn6uh3ft5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4000.102 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "11,542 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1525548146000" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1525548146000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1525548235000"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1525548235000"
webtalk_transmit -clientid 2988550959 -regid "210727995_1777512417_210616669_940" -xml /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
