# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZyboLinux.xdc

# Block Designs: bd/ProcessingSystem/ProcessingSystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem || ORIG_REF_NAME==ProcessingSystem} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_processing_system7_0_0 || ORIG_REF_NAME==ProcessingSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_axi_gpio_0_0/ProcessingSystem_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_axi_gpio_0_0 || ORIG_REF_NAME==ProcessingSystem_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_axi_gpio_1_0/ProcessingSystem_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_axi_gpio_1_0 || ORIG_REF_NAME==ProcessingSystem_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_xlconcat_0_0/ProcessingSystem_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_xlconcat_0_0 || ORIG_REF_NAME==ProcessingSystem_xlconcat_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_ps7_0_axi_periph_0/ProcessingSystem_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==ProcessingSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_rst_ps7_0_100M_0/ProcessingSystem_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==ProcessingSystem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_xbar_0/ProcessingSystem_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_xbar_0 || ORIG_REF_NAME==ProcessingSystem_xbar_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_AXI_Segment_0_0/ProcessingSystem_AXI_Segment_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_AXI_Segment_0_0 || ORIG_REF_NAME==ProcessingSystem_AXI_Segment_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_xadc_wiz_0_0/ProcessingSystem_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_xadc_wiz_0_0 || ORIG_REF_NAME==ProcessingSystem_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/ProcessingSystem/ip/ProcessingSystem_auto_pc_0/ProcessingSystem_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ProcessingSystem_auto_pc_0 || ORIG_REF_NAME==ProcessingSystem_auto_pc_0} -quiet] -quiet

# XDC: bd/ProcessingSystem/ProcessingSystem_ooc.xdc
