# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.srcs/sources_1/bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xci
# IP: The module: 'ProcessingSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.srcs/sources_1/bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ProcessingSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.srcs/sources_1/bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xci
# IP: The module: 'ProcessingSystem_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.srcs/sources_1/bd/ProcessingSystem/ip/ProcessingSystem_processing_system7_0_0/ProcessingSystem_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ProcessingSystem_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
