set_property SRC_FILE_INFO {cfile:/home/daniel/Schreibtisch/Git/Zybo-Linux/Vivado/SimpleLinux/SimpleLinux.srcs/constrs_1/new/SimpleLinux.xdc rfile:../../../SimpleLinux.srcs/constrs_1/new/SimpleLinux.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {GPIO_tri_i[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {GPIO_tri_i[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {GPIO_tri_i[2]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {GPIO_tri_i[3]}]
